name: dart_flutter_project_manager
description: A Flutter project to manage Dart/Flutter projects.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-0 <4.0.0'

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  filesystem_picker: ^4.0.0
  flutter:
    sdk: flutter
  flutterando_metrics: ^5.7.7
  gap: ^3.0.1
  git: ^2.2.1
  go_router: ^12.1.1
  path: ^1.8.3
  path_provider: ^2.1.1
  process_run: ^0.13.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
